- name: Baixar script de instalação do Docker
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Instalar Docker usando script
  shell: bash /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Iniciar e habilitar serviço Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Criar rede Docker para a aplicação
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present

- name: Criar volumes Docker
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - pgdata
    - grafana-data
    - prometheus-data