FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./Front/Front.csproj"
RUN dotnet build "./Front/Front.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./Front/Front.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY "./Front/nginx.conf" /etc/nginx/nginx.conf
