FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["SYKI.sln", "."]
COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["Back/Back.csproj", "Back/"]

RUN dotnet restore "Back/Back.csproj"

COPY . .

WORKDIR "/src/Back"
RUN dotnet publish "Back.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Back.dll"]