FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./Daemon/Daemon.csproj"
RUN dotnet publish "./Daemon/Daemon.csproj" -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5003

ENTRYPOINT [ "dotnet", "Daemon.dll" ]
