- name: Atualizar repositórios apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar pacotes essenciais
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
    state: present

- name: Configurar resolv.conf
  copy:
    content: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'