CREATE SCHEMA db;


CREATE TABLE db.diaristas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    matricula text NOT NULL,
    data_nascimento timestamp with time zone NOT NULL,
    CONSTRAINT pk_diaristas PRIMARY KEY (id)
);


CREATE TABLE db.telefones (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    diarista_id integer NOT NULL,
    numero text NOT NULL,
    CONSTRAINT pk_telefones PRIMARY KEY (id),
    CONSTRAINT fk_telefones_diaristas_diarista_id FOREIGN KEY (diarista_id) REFERENCES db.diaristas (id) ON DELETE CASCADE
);

CREATE TABLE db.enderecos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cidade text NOT NULL,
    bairro text NOT NULL,
    CONSTRAINT pk_enderecos PRIMARY KEY (id)
);

CREATE TABLE db.casas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    endereco_id integer NOT NULL,
    CONSTRAINT pk_casas PRIMARY KEY (id),
    CONSTRAINT fk_casas_enderecos_endereco_id FOREIGN KEY (endereco_id) REFERENCES db.enderecos (id) ON DELETE CASCADE
);


CREATE TABLE db.servicos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    diarista_id integer NOT NULL,
    casa_id integer NOT NULL,
    horas integer NOT NULL,
    data timestamp with time zone NOT NULL,
    CONSTRAINT pk_servicos PRIMARY KEY (id),
    CONSTRAINT fk_servicos_diaristas_diarista_id FOREIGN KEY (diarista_id) REFERENCES db.diaristas (id) ON DELETE CASCADE,
    CONSTRAINT fk_servicos_casas_casa_id FOREIGN KEY (casa_id) REFERENCES db.casas (id) ON DELETE CASCADE
);


CREATE UNIQUE INDEX ix_diaristas_matricula ON db.diaristas (matricula);
CREATE UNIQUE INDEX ix_casas_endereco_id ON db.casas (endereco_id);
CREATE UNIQUE INDEX ix_telefones_numero ON db.telefones (numero);


INSERT INTO db.diaristas (nome, matricula, data_nascimento) VALUES
('Maria', 'F5YHFG517', '1993-11-09'),
('Julia', '6GE4GR6KI', '1999-08-16'),
('Anna', 'R6KIF5YH5', '1974-05-02');

INSERT INTO db.telefones (diarista_id, numero) VALUES
(1, '40028922'),
(1, '85239541'),
(2, '75398745'),
(3, '89632587');

INSERT INTO db.enderecos (cidade, bairro) VALUES
('Caruaru', 'Salgado'),
('Caruaru', 'Indianopolis'),
('Caruaru', 'Boa Vista');

INSERT INTO db.casas (endereco_id) VALUES
(1), (2), (3);

INSERT INTO db.servicos (diarista_id, casa_id, horas, "data") VALUES
(1, 2, 5, '2023-11-06'),
(2, 3, 7, '2023-11-07'),
(1, 3, 7, '2023-11-07');


select * from db.diaristas;
select * from db.telefones;

select * from db.casas;
select * from db.enderecos;

select * from db.servicos;
