// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Syki.Back.Database;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(SykiDbContext))]
    [Migration("20260529020436_Bootstrap")]
    partial class Bootstrap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Syki.Back.Audit.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_trails");

                    b.ToTable("audit_trails", "syki");
                });

            modelBuilder.Entity("Syki.Back.Commands.Domain.Commands.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityId")
                        .HasColumnType("text")
                        .HasColumnName("activity_id");

                    b.Property<int>("BackoffStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("backoff_strategy");

                    b.Property<int>("BaseDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("base_delay_seconds");

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.PrimitiveCollection<List<string>>("Logs")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("logs");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("integer")
                        .HasColumnName("original_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("ProcessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("processor_id");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("retry_attempt");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_commands_institution_id");

                    b.ToTable("commands", "syki");
                });

            modelBuilder.Entity("Syki.Back.Commands.Domain.Commands.CommandBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<int?>("NextCommandId")
                        .HasColumnType("integer")
                        .HasColumnName("next_command_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<int?>("SourceCommandId")
                        .HasColumnType("integer")
                        .HasColumnName("source_command_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_command_batches");

                    b.ToTable("command_batches", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Campi.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_campi");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_campi_institution_id");

                    b.ToTable("campi", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseCurriculums.CourseCurriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_course_curriculums");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_curriculums_course_id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_course_curriculums_institution_id");

                    b.ToTable("course_curriculums", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseCurriculums.CourseCurriculumDiscipline", b =>
                {
                    b.Property<int>("CourseCurriculumId")
                        .HasColumnType("integer")
                        .HasColumnName("course_curriculum_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id");

                    b.Property<byte>("Credits")
                        .HasColumnType("smallint")
                        .HasColumnName("credits");

                    b.Property<byte>("Period")
                        .HasColumnType("smallint")
                        .HasColumnName("period");

                    b.Property<int>("Workload")
                        .HasColumnType("integer")
                        .HasColumnName("workload");

                    b.HasKey("CourseCurriculumId", "DisciplineId")
                        .HasName("pk_course_curriculums_disciplines");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("ix_course_curriculums_disciplines_discipline_id");

                    b.ToTable("course_curriculums_disciplines", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseOfferings.CourseOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_period_id");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int>("CourseCurriculumId")
                        .HasColumnType("integer")
                        .HasColumnName("course_curriculum_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<int>("Session")
                        .HasColumnType("integer")
                        .HasColumnName("session");

                    b.HasKey("Id")
                        .HasName("pk_course_offerings");

                    b.HasIndex("AcademicPeriodId")
                        .HasDatabaseName("ix_course_offerings_academic_period_id");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_course_offerings_campus_id");

                    b.HasIndex("CourseCurriculumId")
                        .HasDatabaseName("ix_course_offerings_course_curriculum_id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_offerings_course_id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_course_offerings_institution_id");

                    b.ToTable("course_offerings", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseType")
                        .HasColumnType("integer")
                        .HasColumnName("course_type");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_courses_institution_id");

                    b.ToTable("courses", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Courses.CourseDiscipline", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id");

                    b.HasKey("CourseId", "DisciplineId")
                        .HasName("pk_courses_disciplines");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("ix_courses_disciplines_discipline_id");

                    b.ToTable("courses_disciplines", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Disciplines.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_disciplines");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_disciplines_code");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_disciplines_institution_id");

                    b.ToTable("disciplines", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.InstitutionRole", b =>
                {
                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("InstitutionId", "RoleId")
                        .HasName("pk_institution_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_institution_roles_role_id");

                    b.ToTable("institution_roles", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.MagicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_magic_links");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_magic_links_user_id");

                    b.ToTable("magic_links", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.ResetPasswordToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reset_password_tokens");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_reset_password_tokens_institution_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_reset_password_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reset_password_tokens_user_id");

                    b.ToTable("reset_password_tokens", (string)null);
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SsoAllowedDomain", b =>
                {
                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<int>("SsoConfigurationId")
                        .HasColumnType("integer")
                        .HasColumnName("sso_configuration_id");

                    b.HasKey("Domain")
                        .HasName("pk_sso_allowed_domains");

                    b.HasIndex("SsoConfigurationId")
                        .HasDatabaseName("ix_sso_allowed_domains_sso_configuration_id");

                    b.ToTable("sso_allowed_domains", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SsoConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer")
                        .HasColumnName("provider_type");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<bool>("RequireSso")
                        .HasColumnType("boolean")
                        .HasColumnName("require_sso");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sso_configurations");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_sso_configurations_institution_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_sso_configurations_public_id");

                    b.ToTable("sso_configurations", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseType")
                        .HasColumnType("integer")
                        .HasColumnName("base_type");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.PrimitiveCollection<List<int>>("Permissions")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("role_name_index");

                    b.HasIndex("OwnerId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_owner_id_normalized_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerId", "NormalizedName"), false);

                    b.ToTable("roles", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text")
                        .HasColumnName("profile_photo");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("InstitutionId", "Id")
                        .HasName("ak_asp_net_users_institution_id_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("users", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserRole", b =>
                {
                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("InstitutionId", "UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.HasIndex("InstitutionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_institution_id_user_id");

                    b.ToTable("user_roles", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Institutions.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_institutions");

                    b.ToTable("institutions", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Periods.AcademicPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndAt")
                        .HasColumnType("date")
                        .HasColumnName("end_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartAt")
                        .HasColumnType("date")
                        .HasColumnName("start_at");

                    b.HasKey("Id")
                        .HasName("pk_academic_periods");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_academic_periods_institution_id");

                    b.ToTable("academic_periods", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Periods.EnrollmentPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndAt")
                        .HasColumnType("date")
                        .HasColumnName("end_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartAt")
                        .HasColumnType("date")
                        .HasColumnName("start_at");

                    b.HasKey("Id")
                        .HasName("pk_enrollment_periods");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_enrollment_periods_institution_id");

                    b.ToTable("enrollment_periods", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Students.StudentCourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseOfferingId")
                        .HasColumnType("integer")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_course_enrollments");

                    b.HasIndex("CourseOfferingId")
                        .HasDatabaseName("ix_student_course_enrollments_course_offering_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_course_enrollments_student_id");

                    b.ToTable("student_course_enrollments", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Students.SykiStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnrollmentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrollment_code");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("YieldCoefficient")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("yield_coefficient");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("EnrollmentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_students_enrollment_code");

                    b.HasIndex("InstitutionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_institution_id_user_id");

                    b.ToTable("students", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Teachers.SykiTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("InstitutionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_institution_id_user_id");

                    b.ToTable("teachers", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Teachers.TeacherCampus", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.HasKey("TeacherId", "CampusId")
                        .HasName("pk_teachers_campi");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_teachers_campi_campus_id");

                    b.ToTable("teachers_campi", "syki");
                });

            modelBuilder.Entity("Syki.Back.Domain.Teachers.TeacherDiscipline", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id");

                    b.HasKey("TeacherId", "DisciplineId")
                        .HasName("pk_teachers_disciplines");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("ix_teachers_disciplines_discipline_id");

                    b.ToTable("teachers_disciplines", "syki");
                });

            modelBuilder.Entity("Syki.Back.Commands.Domain.Commands.Command", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commands_institutions_institution_id");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Syki.Back.Domain.Campi.Campus", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("Campi")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campi_institutions_institution_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseCurriculums.CourseCurriculum", b =>
                {
                    b.HasOne("Syki.Back.Domain.Courses.Course", "Course")
                        .WithMany("CourseCurriculums")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_curriculums_courses_course_id");

                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("CourseCurriculums")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_curriculums_institutions_institution_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseCurriculums.CourseCurriculumDiscipline", b =>
                {
                    b.HasOne("Syki.Back.Domain.CourseCurriculums.CourseCurriculum", null)
                        .WithMany("Links")
                        .HasForeignKey("CourseCurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_curriculums_disciplines_course_curriculums_course_cu");

                    b.HasOne("Syki.Back.Domain.Disciplines.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_curriculums_disciplines_disciplines_discipline_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseOfferings.CourseOffering", b =>
                {
                    b.HasOne("Syki.Back.Domain.Periods.AcademicPeriod", "AcademicPeriod")
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_academic_periods_academic_period_id");

                    b.HasOne("Syki.Back.Domain.Campi.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_campi_campus_id");

                    b.HasOne("Syki.Back.Domain.CourseCurriculums.CourseCurriculum", "CourseCurriculum")
                        .WithMany()
                        .HasForeignKey("CourseCurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_course_curriculums_course_curriculum_id");

                    b.HasOne("Syki.Back.Domain.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_courses_course_id");

                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("CourseOfferings")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_offerings_institutions_institution_id");

                    b.Navigation("AcademicPeriod");

                    b.Navigation("Campus");

                    b.Navigation("Course");

                    b.Navigation("CourseCurriculum");
                });

            modelBuilder.Entity("Syki.Back.Domain.Courses.Course", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("Courses")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_institutions_institution_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Courses.CourseDiscipline", b =>
                {
                    b.HasOne("Syki.Back.Domain.Courses.Course", null)
                        .WithMany("Links")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_disciplines_courses_course_id");

                    b.HasOne("Syki.Back.Domain.Disciplines.Discipline", null)
                        .WithMany("Links")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_disciplines_disciplines_discipline_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Disciplines.Discipline", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("Disciplines")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disciplines_institutions_institution_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.InstitutionRole", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_institution_roles_institutions_institution_id");

                    b.HasOne("Syki.Back.Domain.Identity.SykiRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_institution_roles_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.MagicLink", b =>
                {
                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_magic_links_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.ResetPasswordToken", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reset_password_tokens_institutions_institution_id");

                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reset_password_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SsoAllowedDomain", b =>
                {
                    b.HasOne("Syki.Back.Domain.Identity.SsoConfiguration", null)
                        .WithMany("AllowedDomains")
                        .HasForeignKey("SsoConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sso_allowed_domains_sso_configurations_sso_configuration_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SsoConfiguration", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sso_configurations_institutions_institution_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiRole", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_roles_institutions_owner_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiRoleClaim", b =>
                {
                    b.HasOne("Syki.Back.Domain.Identity.SykiRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUser", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_institutions_institution_id");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserClaim", b =>
                {
                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserLogin", b =>
                {
                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserRole", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_institutions_institution_id");

                    b.HasOne("Syki.Back.Domain.Identity.SykiRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Institution");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SykiUserToken", b =>
                {
                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Periods.AcademicPeriod", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("AcademicPeriods")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_periods_institutions_institution_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Periods.EnrollmentPeriod", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("EnrollmentPeriods")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_periods_institutions_institution_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Students.StudentCourseEnrollment", b =>
                {
                    b.HasOne("Syki.Back.Domain.CourseOfferings.CourseOffering", null)
                        .WithMany()
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_course_enrollments_course_offerings_course_offering");

                    b.HasOne("Syki.Back.Domain.Students.SykiStudent", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_course_enrollments_students_student_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Students.SykiStudent", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("Students")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_institutions_institution_id");

                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", "User")
                        .WithOne()
                        .HasForeignKey("Syki.Back.Domain.Students.SykiStudent", "InstitutionId", "UserId")
                        .HasPrincipalKey("Syki.Back.Domain.Identity.SykiUser", "InstitutionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_asp_net_users_institution_id_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syki.Back.Domain.Teachers.SykiTeacher", b =>
                {
                    b.HasOne("Syki.Back.Domain.Institutions.Institution", null)
                        .WithMany("Teachers")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_institutions_institution_id");

                    b.HasOne("Syki.Back.Domain.Identity.SykiUser", "User")
                        .WithOne()
                        .HasForeignKey("Syki.Back.Domain.Teachers.SykiTeacher", "InstitutionId", "UserId")
                        .HasPrincipalKey("Syki.Back.Domain.Identity.SykiUser", "InstitutionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_asp_net_users_institution_id_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Syki.Back.Domain.Teachers.TeacherCampus", b =>
                {
                    b.HasOne("Syki.Back.Domain.Campi.Campus", null)
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_campi_campi_campus_id");

                    b.HasOne("Syki.Back.Domain.Teachers.SykiTeacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_campi_teachers_teacher_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.Teachers.TeacherDiscipline", b =>
                {
                    b.HasOne("Syki.Back.Domain.Disciplines.Discipline", null)
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_disciplines_disciplines_discipline_id");

                    b.HasOne("Syki.Back.Domain.Teachers.SykiTeacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_disciplines_teachers_teacher_id");
                });

            modelBuilder.Entity("Syki.Back.Domain.CourseCurriculums.CourseCurriculum", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Syki.Back.Domain.Courses.Course", b =>
                {
                    b.Navigation("CourseCurriculums");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Syki.Back.Domain.Disciplines.Discipline", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Syki.Back.Domain.Identity.SsoConfiguration", b =>
                {
                    b.Navigation("AllowedDomains");
                });

            modelBuilder.Entity("Syki.Back.Domain.Institutions.Institution", b =>
                {
                    b.Navigation("AcademicPeriods");

                    b.Navigation("Campi");

                    b.Navigation("CourseCurriculums");

                    b.Navigation("CourseOfferings");

                    b.Navigation("Courses");

                    b.Navigation("Disciplines");

                    b.Navigation("EnrollmentPeriods");

                    b.Navigation("Students");

                    b.Navigation("Teachers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
